name: Send Email from JSON Payload

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'JSON payload with report content'
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Parse JSON and set outputs
        id: parse_payload
        run: |
          echo "Parsing JSON input..."
          echo '${{ github.event.inputs.payload }}' > payload.json

          title=$(jq -r '.title' payload.json)
          email=$(jq -r '.email' payload.json)
          exec_summary=$(jq -r '.exec_summary' payload.json)
          introduction=$(jq -r '.introduction' payload.json)
          findings=$(jq -r '.finding' payload.json)
          recommendation=$(jq -r '.recommendation' payload.json)
          current_date=$(date +"%Y-%m-%d")

          echo "title=$title"           >> $GITHUB_OUTPUT
          echo "email=$email"           >> $GITHUB_OUTPUT
          echo "exec_summary=$exec_summary" >> $GITHUB_OUTPUT
          echo "introduction=$introduction" >> $GITHUB_OUTPUT
          echo "findings=$findings"     >> $GITHUB_OUTPUT
          echo "recommendation=$recommendation" >> $GITHUB_OUTPUT
          echo "current_date=$current_date"     >> $GITHUB_OUTPUT

      - name: Generate report.qmd from template
        run: |
          cp template.qmd report.qmd
          sed -i "s/{title}/${{ steps.parse_payload.outputs.title }}/g" report.qmd
          sed -i "s/{current_date}/${{ steps.parse_payload.outputs.current_date }}/g" report.qmd
          sed -i "s/{executive_summary}/${{ steps.parse_payload.outputs.exec_summary }}/g" report.qmd
          sed -i "s/{introduction}/${{ steps.parse_payload.outputs.introduction }}/g" report.qmd
          sed -i "s/{findings}/${{ steps.parse_payload.outputs.findings }}/g" report.qmd
          sed -i "s/{recommendation}/${{ steps.parse_payload.outputs.recommendation }}/g" report.qmd

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2 # Install Quarto via official action

      - name: Render report.qmd to PDF
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: latex
          path: report.qmd

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3 # Pin latex-action to specific version
        with:
          root_file: report.tex
          latexmk_use_lualatex: true

      - name: Cache LaTeX Docker Image
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/docker
          key: ${{ runner.os }}-latex-docker-${{ hashFiles('Dockerfile') }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4.3.1 # Pin upload artifact action
        with:
          name: rendered-pdf
          path: report.pdf

      - name: Send Email with Attachment
        uses: dawidd6/action-send-mail@v3.11.0
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_SERVER_PORT }}
          secure: true
          username: ${{ vars.EMAIL_ADDRESS }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          convert_markdown: true
          subject: "${{ steps.parse_payload.outputs.title }}"
          from: ${{ vars.EMAIL_NAME }}
          to: ${{ steps.parse_payload.outputs.email }}
          body: |
            Hai Orang Baik,

            Berikut adalah hasil analisisku terkait kondisi kamu:

            > ${{ steps.parse_payload.outputs.exec_summary }}

            Salam hangat,

            Lyna  

            **Virtual Assistant**  
            Konsulin  
            *Psychological Kit in Your Pocket*  
          attachments: report.pdf # Attach the rendered PDF

      - name: Cleanup temporary files
        if: always()
        run: rm -f report.qmd report.pdf report.tex
